name: songs-library

services:
  backend:
    build: backend
    ports:
      - 80:80
    volumes:
      -  ./backend:/var/www/html/
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

