name: songs-library

services:
  db:
    image: mysql:8.4.0
    env_files: .env
    container_name: songs-library_db
    restart: always
    volumes:
      - songs-library_db:/var/lib/mysql
  frontend:
    
